run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - prealloc
    - exportloopref

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gofmt:
    simplify: true
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - govet
    - path: cmd/api/main.go
      linters:
        - noctx
  max-issues-per-linter: 50
  max-same-issues: 10
